feat (wave): add Wave adapter to docs
Finch-API/finch-docs pull request #112
Opened 2022-08-19 16:46 UTC by jason-gill00

Add Wave to https://developer.tryfinch.com/docs/reference/96f5be9e0ec1a-providers

2022-08-19 16:48 UTC, alexromano commented
we should add compatibility sections as well yeah?

2022-08-19 16:59 UTC, jason-gill00 commented
> we should add compatibility sections as well yeah?

I think @seii updated the compatibility screenshots. 

https://developer.tryfinch.com/docs/reference/0517ab806dda4-compatibility

2022-08-22 16:21 UTC, seii commented
@jason-gill00 @alexromano Yes, I had updated the Compatibility page images from the spreadsheet. I didn't realize at the time that Wave wasn't listed in the Providers page, I'll keep an eye on that next time.

2022-08-22 16:22 UTC, alexromano commented
this integration isn't launched yet. why is it shown in the public docs?

2022-08-22 17:16 UTC, seii commented
@alexromano Because it was in the Compatibility spreadsheet, and that spreadsheet has never previously contained sensitive information to my knowledge. If we are going to populate that information prior to the public release of an adapter, then I can ask Engineering before updating those images in the future.

2022-09-09 04:57 UTC, sshariff01 approved these changes

2022-09-09 04:58 UTC, sshariff01 requested changes
Actually https://github.com/Finch-API/finch-docs/blob/main/docs/Development-Guides/Providers.md?plain=1#L188 needs to be removed too.

2022-09-09 05:00 UTC, sshariff01 commented on docs/Development-Guides/Providers.md
> +Wave | `wave` | <span style="color:darkgreen">Automated</span> | <span style="color:goldenrod">Assisted</span>
```suggestion
Wave Payroll | `wave` | <span style="color:darkgreen">Automated</span> | <span style="color:goldenrod">Assisted</span>
```

2022-09-09 17:34 UTC, sshariff01 approved these changes

2022-09-09 17:34 UTC, merged