add auth fallback to docs
Finch-API/finch-docs pull request #182
Opened 2023-03-15 21:45 UTC by alexromano

2023-03-17 01:44 UTC, seii requested changes
Mostly good, suggested a few edits for clarity

2023-03-17 01:44 UTC, seii commented on docs/Development-Guides/Auth-Fallback.md
> +Auth Fallback employers to authorize through Finch Connect even when Finch is experiencing intermittent issues with provider integrations. If an employer attempts to authorize through Finch Connect’s
Suggested: "Auth Fallback allows employers..."

2023-03-17 01:44 UTC, seii commented on docs/Development-Guides/Auth-Fallback.md
> +Yes, this is an opt-in feature. The tradeoff is that when these intermittent issues do occur, your customers will have no way of connecting their accounts until the issues are resolved.
Suggested: "The tradeoff to keeping the current, non-Fallback, behavior is that..."

2023-03-17 01:44 UTC, seii commented on docs/Development-Guides/Auth-Fallback.md
> +**Note that if you choose to opt out, Finch’s ADP Workforce now integration not be available to your customers through Finch Connect.**
Suggested: "...if you choose not to opt in..."

(Technically nobody chooses to opt out but can only choose to opt in, based on the wording already present above.)

2023-03-17 01:44 UTC, seii commented on docs/Development-Guides/Auth-Fallback.md
> +Auth issues occur for a variety of reasons. The provider backends that Finch is integrating with are often legacy systems, meaning they can often be unreliable. Finch attempts to smooth over these ga
Suggested: Hyperlink to docs for Data Sync page for the "data sync" phrase.

2023-03-17 18:04 UTC, seii approved these changes

2023-03-17 18:33 UTC, alexromano commented
@seii added a new line to call out that this only applies to credential auth

2023-03-17 20:23 UTC, seii approved these changes

2023-03-27 15:26 UTC, jerzzhang requested changes
I put everything through ChatGPT for grammar and clarity. See below if you want to replace parts.

Configuring Authentication Methods
Finch offers multiple authentication methods to accommodate various integration preferences of end employers. These methods include credentials-based authentication, OAuth, and direct API token input. Each method provides a distinct balance between reliability and data accessibility.

As a developer, you have the flexibility to decide which authentication methods to make available for your end customers and their order of priority. You can set primary and secondary authentication methods for each provider, and even hide specific methods if desired. For example, if you want to present only the OAuth method to BambooHR customers, Finch can conceal the credentials-based authentication method in Finch Connect. To request a custom authentication configuration, please contact your Finch representative, who will be happy to assist you.

Authentication Fallback Feature
The Authentication Fallback feature is an opt-in option for Scale tier customers. It enables employers to authorize through Finch Connect even during intermittent issues with provider integrations. This feature is applicable only to credentials-based authentication methods and does not extend to direct API token entry or OAuth.

When an employer encounters an error while attempting to authenticate via Finch Connect's automated flow, Finch Connect will display manual connection instructions after three failed attempts*. This process involves the employer adding Finch as a third-party user in their system. Once Finch accepts the invitation and sets up the account, the data for the connection will flow through the Finch API, just like any other automated connection. The primary distinction is that your application will receive a 202 response when making requests with that token until the connection is established on Finch's end. Ensure that your application is configured to handle 202 response codes from Finch. To enable this feature, please reach out to your Finch account manager.

*The number of errors before displaying the fallback screen is adjustable. While the default value is set to three for every provider, this may change over time.

2023-03-27 17:51 UTC, merged