docs: Add use case sequence diagrams, Best Practices section, YTD Wages guide + moves three guides to Best Practices
Finch-API/finch-docs pull request #186
Opened 2023-03-27 13:35 UTC by logangingerich

Adds a new development guide that presents sequences diagrams to demonstrate the logic for various common use cases. Starting with diagrams for Finch Connect + MFA, Calculating YTD Gross Wages, Automated Benefits and Assisted Benefits.

2023-03-30 00:54 UTC, jerzzhang commented
I wonder if we should move these flow diagrams to the appropriate location in the Docs--
- Finch Connect + MFA -> https://developer.tryfinch.com/docs/reference/a2c944f1041f6-automated-connect-flow
- YTD Calculations -> Create a new Development Guide similar to https://developer.tryfinch.com/docs/reference/769fd850853dd-reconciling-employees but for YTD calculations
- Automated Benefits and Assisted Benefits -> https://developer.tryfinch.com/docs/reference/67f5ed02d81fe-integrating-the-benefits-api

2023-03-30 20:05 UTC, tylernix commented
@logangingerich Can you create a best practices section? A few docs that are currently in the "Development Guides" section would better go under "Best Practices":
- Re-authentication Flow
- Multi-account Flow
- Reconciling Employees
- [Calculatating Year-To-Date Gross Wages]

2023-04-02 16:51 UTC, jerzzhang approved these changes
LGTM!

2023-04-04 15:01 UTC, tylernix requested changes

2023-04-04 15:15 UTC, tylernix approved these changes

2023-04-07 17:45 UTC, alexromano approved these changes

2023-04-07 18:00 UTC, merged